import { createContext, useContext, useState, ReactNode } from 'react';
import { challengePageTranslations } from '@/data/translations.de';

export type Language = 'en' | 'de' | 'fr' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    'nav.home': 'Home',
    'nav.epistemology': 'Epistemology',
    'nav.challenges': 'Challenges',
    'nav.cognitive-biases': 'Cognitive Biases',
    'nav.logical-fallacies': 'Logical Fallacies',
    'nav.critical-thinking': 'Critical Thinking',
    'nav.consciousness': 'Consciousness',
    'nav.solutions': 'Solutions',
    'nav.street-epistemology': 'Street Epistemology',
    'nav.socratic-questioning': 'Socratic Questioning',
    'nav.scientific-method': 'Scientific Method',
    'nav.comedians': 'Comedians',
    'nav.language': 'Language',
    'home.title': 'Objective Reality',
    'home.subtitle': 'Understanding cognitive biases, logical fallacies, and consciousness',
    'home.description': 'Explore the systematic patterns of deviation from rationality in judgment and decision-making.',
    'epistemology.title': 'Epistemology',
    'epistemology.description': 'How can we know if something is actually true?',
    'challenges.title': 'Challenges',
    'challenges.description': 'Barriers that separate us from objective reality',
    'biases.title': 'Cognitive Biases',
    'biases.description': 'Systematic errors in thinking that affect decisions and judgments',
    'fallacies.title': 'Logical Fallacies',
    'fallacies.description': 'Flawed reasoning patterns that undermine the logic of an argument',
    'consciousness.title': 'Consciousness',
    'consciousness.description': 'Understanding levels of human consciousness and development',
    'consensus.title': 'Scientific Consensus',
    'consensus.description': 'Critical analysis of scientific authority and groupthink',
    'solutions.title': 'Solutions',
    'solutions.description': 'Practical tools and methods to overcome cognitive limitations',
    // Challenges content
    'challenges.why.title': 'Why Understanding These Challenges Matters',
    'challenges.personal.title': 'Personal Growth',
    'challenges.personal.description': 'Self-awareness of our cognitive limitations leads to better decision-making',
    'challenges.societal.title': 'Societal Progress',
    'challenges.societal.description': 'An informed population makes better collective decisions',
    'challenges.discourse.title': 'Improved Discourse',
    'challenges.discourse.description': 'Recognizing fallacies leads to more productive discussions',
    'challenges.scientific.title': 'Scientific Advancement',
    'challenges.scientific.description': 'Critical thinking promotes better research and innovation',
    'challenges.start_journey': 'Start Your Journey',
    'challenges.start_journey.description': 'Begin by exploring the most fundamental challenges to clear thinking.',
    'challenges.explore_biases': 'Explore Cognitive Biases',
    'challenges.study_fallacies': 'Study Logical Fallacies',
    'challenges.advanced_topics': 'Advanced Topics',
    'challenges.advanced_topics.description': 'Dive deeper into systemic and cultural barriers to objective thinking.',
    'challenges.scientific_consensus': 'Scientific Consensus',
    'challenges.information_suppression': 'Information Suppression',
    
    // Individual challenge items
    'challenge.indoctrination.title': 'Indoctrination',
    'challenge.indoctrination.description': 'Systematic influence by parents, state/school, and media that shapes our worldview from childhood.',
    'challenge.consensus.title': 'Scientific Consensus as Golden Calf',
    'challenge.consensus.description': 'Blind acceptance of scientific consensus without critical evaluation of underlying assumptions.',
    'challenge.cognitive_biases.title': 'Cognitive Biases',
    'challenge.cognitive_biases.description': 'Systematic errors in thinking that affect decisions and judgments.',
    'challenge.logical_fallacies.title': 'Logical Fallacies',
    'challenge.logical_fallacies.description': 'Flawed reasoning patterns that undermine the logic of arguments.',
    'challenge.propaganda.title': 'Propaganda',
    'challenge.propaganda.description': 'Information designed to promote particular political causes or points of view.',
    'challenge.censorship.title': 'Censorship',
    'challenge.censorship.description': 'Suppression of information and ideas that challenge established narratives.',
    'challenge.dogmas.title': 'Dogmatic Beliefs',
    'challenge.dogmas.description': 'Rigid adherence to principles without consideration of evidence or alternative viewpoints.',
    'challenge.co_evolution.title': 'Co-evolution with Religion',
    'challenge.co_evolution.description': 'How religious thinking patterns influence secular reasoning and decision-making.',
    'challenge.lazy_thinking.title': 'Lazy Thinking',
    'challenge.lazy_thinking.description': 'Mental shortcuts and avoidance of deep analysis leading to poor conclusions.',
    'challenge.psychological_weakness.title': 'Psychological Weaknesses',
    'challenge.psychological_weakness.description': 'Human psychological vulnerabilities that can be exploited to manipulate thinking.',
    'challenge.ego.title': 'Ego',
    'challenge.ego.description': 'How personal identity and self-image interfere with objective reasoning.',
    
    // Category translations
    'category.too_much_information': 'Too Much Information',
    'category.not_enough_meaning': 'Not Enough Meaning',
    'category.need_to_act_fast': 'Need to Act Fast',
    'category.what_to_remember': 'What Should We Remember',
    'category.relevance': 'Relevance',
    'category.presumption': 'Presumption',
    'category.weak_inference': 'Weak Inference',
    'category.causal': 'Causal',
    'category.formal': 'Formal',
    'category.conditional': 'Conditional',
    // Search and filter
    'search.placeholder': 'Search...',
    'filter.all': 'All Categories',
    'filter.by_category': 'Filter by category',
    'showing_results': 'Showing {count} of {total}',
    'no_results': 'No results found',
    'clear_filters': 'Clear Filters',
    'learn_more': 'Learn More',
    'example': 'Example',
    // Common actions
    'back': 'Back',
    'next': 'Next',
    'previous': 'Previous',
    'close': 'Close',
    'open': 'Open',
    
    // Challenge page translations (English) - adding missing keys
    'scientificConsensus.criticalObservation': 'Critical Observation',
    'scientificConsensus.criticalText': 'It is quite possible that a significant portion of what we consider "scientific consensus" will be proven wrong in the coming decades.',
    'scientificConsensus.consensusVsDogma': 'Scientific Consensus vs. Dogma',
    'scientificConsensus.consensusVsDogmaText': 'Scientific consensus differs from religious dogma because it can be updated with new evidence. However, this doesn\'t mean we should accept all current consensus uncritically.',
    'scientificConsensus.balancedApproach': 'A Balanced Approach',
    'scientificConsensus.balancedApproachText': 'The goal isn\'t to reject science, but to maintain healthy skepticism and understand the limitations of current knowledge.',
    'scientificConsensus.historicalPattern': 'Historical Pattern',
    'scientificConsensus.practicalGuidelines': 'Practical Guidelines',
    'scientificConsensus.field.mathematics': 'Mathematics',
    'scientificConsensus.field.mathematics.desc': 'Close to impossible to cheat at basics',
    'scientificConsensus.field.physics': 'Physics (Classical)',
    'scientificConsensus.field.physics.desc': 'Well-established laws with strong evidence',
    'scientificConsensus.field.chemistry': 'Chemistry',
    'scientificConsensus.field.chemistry.desc': 'Solid experimental foundation',
    'scientificConsensus.field.biology': 'Biology',
    'scientificConsensus.field.biology.desc': 'Complex systems with many variables',
    'scientificConsensus.field.medicine': 'Medicine',
    'scientificConsensus.field.medicine.desc': 'Individual variation and complexity',
    'scientificConsensus.field.history': 'History',
    'scientificConsensus.field.history.desc': 'Interpretation varies, but facts remain',
    'scientificConsensus.field.psychology': 'Psychology',
    'scientificConsensus.field.psychology.desc': 'Replication crisis and subjective elements',
    'scientificConsensus.field.nutrition': 'Nutrition Science',
    'scientificConsensus.field.nutrition.desc': 'Conflicting studies and industry influence',
    'scientificConsensus.field.economics': 'Economics',
    'scientificConsensus.field.economics.desc': 'Human behavior and complex systems',
    'scientificConsensus.field.climate': 'Climate Science',
    'scientificConsensus.field.climate.desc': 'Complex models with many variables and political influence',
    'scientificConsensus.field.social': 'Social Sciences',
    'scientificConsensus.field.social.desc': 'Cultural bias and methodology issues',
    
    'censorship.politicalCorrectnessAlert': '"Political Correctness" is often a euphemism for censorship and thought control.',
    'censorship.typesOfCensorship': 'Types of Modern Censorship',
    'censorship.propagandaLanguage': 'Propaganda Language Alert',
    'censorship.propagandaLanguageDesc': 'These labels are part of indoctrination and propaganda language and should immediately raise red flags. Remember: who for some is a "freedom fighter", for others is a "terrorist".',
    'censorship.sophistication': 'The Sophistication Problem',
    'censorship.sophisticationText': 'Modern censorship is becoming more sophisticated and harder to detect. Traditional overt censorship is being replaced by subtle manipulation techniques.',
    'censorship.detection': 'How to Detect Censorship',
    'censorship.importanceOfFreeExpression': 'The Importance of Free Expression',
    'censorship.type.politicalCorrectness': 'Political Correctness',
    'censorship.type.politicalCorrectness.desc': 'Thought police that kills creative and progressive discussions out of fear of offending someone.',
    'censorship.type.algorithmicBias': 'Algorithmic Bias',
    'censorship.type.algorithmicBias.desc': 'Biased algorithms that suppress certain viewpoints while promoting others.',
    'censorship.type.shadowBanning': 'Ghosting/Shadow Banning',
    'censorship.type.shadowBanning.desc': 'Making content invisible without notifying the author or audience.',
    'censorship.type.labelSuppression': 'Label-Based Suppression',
    'censorship.type.labelSuppression.desc': 'Dismissing content by labeling it as "hate speech", "disinformation", or "conspiracy theory".',
    'censorship.type.memoryHole': 'Memory Hole',
    'censorship.type.memoryHole.desc': 'Removing historical information or past statements from public record.',
    'censorship.type.deplatforming': 'Deplatforming',
    'censorship.type.deplatforming.desc': 'Removing individuals from communication platforms entirely.',
    'censorship.label.hateSpeech': 'Hate Speech',
    'censorship.label.hateSpeech.reality': 'Often used to silence legitimate criticism or unpopular opinions',
    'censorship.label.disinformation': 'Disinformation', 
    'censorship.label.disinformation.reality': 'May be applied to information that challenges official narratives',
    'censorship.label.conspiracyTheory': 'Conspiracy Theory',
    'censorship.label.conspiracyTheory.reality': 'Sometimes used to dismiss valid questions about official explanations',
    'censorship.label.moderate': 'Moderate',
    'censorship.label.moderate.reality': 'Subjective term that depends entirely on the observer\'s perspective',
    'censorship.growingUp.title': 'Growing Up Intellectually',
    'censorship.growingUp.text': 'You have the right to be offended. Now grow up and start dealing with the challenges this life is throwing at you. Not being offended anymore is part of growing up.',
    'censorship.detection.informationPatterns': 'Information Patterns',
    'censorship.detection.platformBehavior': 'Platform Behavior',
    'censorship.detection.socialSignals': 'Social Signals',
    'propaganda.title': 'Propaganda',
    'propaganda.subtitle': 'Recognizing and resisting modern information warfare',
    'propaganda.definition': 'What is Propaganda?',
    'propaganda.definitionText': 'Propaganda is the systematic dissemination of information, ideas, or rumors to help or harm an institution, cause, or person. In today\'s world, it has become more subtle and pervasive than ever before.',
    
    'scientificConsensus.title': 'Scientific Consensus',
    'scientificConsensus.subtitle': 'A personal assessment of the reliability of scientific knowledge',
    
    'indoctrination.title': 'Indoctrination',
    'indoctrination.subtitle': 'The systematic conditioning of beliefs',
    
    'censorship.title': 'Censorship',
    'censorship.subtitle': 'Modern forms of information control',
    
    'comedians.title': 'Comedians',
    'comedians.subtitle': 'The modern court jesters of truth',
    
    'streetEpistemology.title': 'Street Epistemology',
    'streetEpistemology.subtitle': 'A method for examining beliefs through Socratic questioning',
    
    'dogmaticBeliefs.title': 'Dogmatic Beliefs',
    'dogmaticBeliefs.subtitle': 'Recognizing and overcoming rigid thinking',
    
    'scientificMethod.title': 'The Scientific Method',
    'scientificMethod.subtitle': 'A tool for objective truth-seeking',
    
    'lazyThinking.title': 'Lazy Thinking',
    'lazyThinking.subtitle': 'The cognitive epidemic of our time',
    
    'socraticQuestioning.title': 'Socratic Questioning',
    'socraticQuestioning.subtitle': 'The art of disciplined questioning',
    
    'coEvolution.title': 'Co-Evolution',
    'coEvolution.subtitle': 'How religious thinking patterns survive in secular contexts',
    
    'psychologicalWeakness.title': 'Psychological Weaknesses',
    'psychologicalWeakness.subtitle': 'Human vulnerabilities that can be exploited',
    
    'ego.title': 'Ego',
    'ego.subtitle': 'How personal identity interferes with objective reasoning',
  },
  de: {
    'nav.home': 'Startseite',
    'nav.epistemology': 'Erkenntnistheorie',
    'nav.challenges': 'Herausforderungen',
    'nav.cognitive-biases': 'Kognitive Verzerrungen',
    'nav.logical-fallacies': 'Logische Fehlschlüsse',
    'nav.critical-thinking': 'Kritisches Denken',
    'nav.consciousness': 'Bewusstsein',
    'nav.solutions': 'Lösungen',
    'nav.street-epistemology': 'Straßenepistemologie',
    'nav.socratic-questioning': 'Sokratisches Hinterfragen',
    'nav.scientific-method': 'Wissenschaftliche Methode',
    'nav.comedians': 'Komiker',
    'nav.consensus': 'Wissenschaftlicher Konsens',
    'nav.censorship': 'Zensur',
    'nav.language': 'Sprache',
    'home.title': 'Objektive Realität',
    'home.subtitle': 'Verständnis von kognitiven Verzerrungen, logischen Fehlschlüssen und Bewusstsein',
    'home.description': 'Entdecken Sie systematische Abweichungsmuster von der Rationalität in Urteilsfindung und Entscheidungsfindung.',
    'epistemology.title': 'Erkenntnistheorie',
    'epistemology.description': 'Wie können wir wissen, ob etwas tatsächlich wahr ist?',
    'challenges.title': 'Herausforderungen',
    'challenges.description': 'Barrieren, die uns von der objektiven Realität trennen',
    'biases.title': 'Kognitive Verzerrungen',
    'biases.description': 'Systematische Denkfehler, die Entscheidungen und Urteile beeinflussen',
    'fallacies.title': 'Logische Fehlschlüsse',
    'fallacies.description': 'Fehlerhafte Argumentationsmuster, die die Logik eines Arguments untergraben',
    'consciousness.title': 'Bewusstsein',
    'consciousness.description': 'Verständnis der Ebenen menschlichen Bewusstseins und Entwicklung',
    'consensus.title': 'Wissenschaftlicher Konsens',
    'consensus.description': 'Kritische Analyse wissenschaftlicher Autorität und Gruppendenken',
    'solutions.title': 'Lösungen',
    'solutions.description': 'Praktische Werkzeuge und Methoden zur Überwindung kognitiver Beschränkungen',
    // Challenges content
    'challenges.why.title': 'Warum diese Herausforderungen verstehen wichtig ist',
    'challenges.personal.title': 'Persönliches Wachstum',
    'challenges.personal.description': 'Selbsterkenntnis über unsere kognitiven Grenzen führt zu besserer Entscheidungsfindung',
    'challenges.societal.title': 'Gesellschaftlicher Fortschritt',
    'challenges.societal.description': 'Eine informierte Bevölkerung trifft bessere kollektive Entscheidungen',
    'challenges.discourse.title': 'Verbesserter Diskurs',
    'challenges.discourse.description': 'Das Erkennen von Fehlschlüssen führt zu produktiveren Diskussionen',
    'challenges.scientific.title': 'Wissenschaftlicher Fortschritt',
    'challenges.scientific.description': 'Kritisches Denken fördert bessere Forschung und Innovation',
    'challenges.start_journey': 'Beginnen Sie Ihre Reise',
    'challenges.start_journey.description': 'Beginnen Sie mit der Erforschung der grundlegendsten Hindernisse für klares Denken.',
    'challenges.explore_biases': 'Kognitive Verzerrungen erkunden',
    'challenges.study_fallacies': 'Logische Fehlschlüsse studieren',
    'challenges.advanced_topics': 'Fortgeschrittene Themen',
    'challenges.advanced_topics.description': 'Vertiefen Sie sich in systemische und kulturelle Barrieren für objektives Denken.',
    'challenges.scientific_consensus': 'Wissenschaftlicher Konsens',
    'challenges.information_suppression': 'Informationsunterdrückung',
    
    // Individual challenge items
    'challenge.indoctrination.title': 'Indoktrinierung',
    'challenge.indoctrination.description': 'Systematische Beeinflussung durch Eltern, Staat/Schule und Medien, die unser Weltbild von Kindheit an prägt.',
    'challenge.consensus.title': 'Wissenschaftlicher Konsens als Goldenes Kalb',
    'challenge.consensus.description': 'Blinde Akzeptanz des wissenschaftlichen Konsenses ohne kritische Bewertung zugrundeliegender Annahmen.',
    'challenge.cognitive_biases.title': 'Kognitive Verzerrungen',
    'challenge.cognitive_biases.description': 'Systematische Denkfehler, die Entscheidungen und Urteile beeinflussen.',
    'challenge.logical_fallacies.title': 'Logische Fehlschlüsse',
    'challenge.logical_fallacies.description': 'Fehlerhafte Argumentationsmuster, die die Logik von Argumenten untergraben.',
    'challenge.propaganda.title': 'Propaganda',
    'challenge.propaganda.description': 'Informationen zur Förderung bestimmter politischer Anliegen oder Standpunkte.',
    'challenge.censorship.title': 'Zensur',
    'challenge.censorship.description': 'Unterdrückung von Informationen und Ideen, die etablierte Narrative herausfordern.',
    'challenge.dogmas.title': 'Dogmatische Überzeugungen',
    'challenge.dogmas.description': 'Starres Festhalten an Prinzipien ohne Berücksichtigung von Beweisen oder alternativen Standpunkten.',
    'challenge.co_evolution.title': 'Ko-Evolution mit Religion',
    'challenge.co_evolution.description': 'Wie religiöse Denkmuster säkulares Denken und Entscheidungsfindung beeinflussen.',
    'challenge.lazy_thinking.title': 'Träges Denken',
    'challenge.lazy_thinking.description': 'Mentale Abkürzungen und Vermeidung tiefgreifender Analysen führen zu schlechten Schlussfolgerungen.',
    'challenge.psychological_weakness.title': 'Psychologische Schwächen',
    'challenge.psychological_weakness.description': 'Menschliche psychologische Schwachstellen, die zur Manipulation des Denkens ausgenutzt werden können.',
    'challenge.ego.title': 'Ego',
    'challenge.ego.description': 'Wie persönliche Identität und Selbstbild objektives Denken beeinträchtigen.',
    
    // Category translations
    'category.too_much_information': 'Zu viele Informationen',
    'category.not_enough_meaning': 'Nicht genug Bedeutung',
    'category.need_to_act_fast': 'Schnell handeln müssen',
    'category.what_to_remember': 'Was sollten wir uns merken',
    'category.relevance': 'Relevanz',
    'category.presumption': 'Vermutung',
    'category.weak_inference': 'Schwache Schlussfolgerung',
    'category.causal': 'Kausal',
    'category.formal': 'Formal',
    'category.conditional': 'Bedingt',
    // Search and filter
    'search.placeholder': 'Suchen...',
    'filter.all': 'Alle Kategorien',
    'filter.by_category': 'Nach Kategorie filtern',
    'showing_results': 'Zeige {count} von {total}',
    'no_results': 'Keine Ergebnisse gefunden',
    'clear_filters': 'Filter löschen',
    'learn_more': 'Mehr erfahren',
    'example': 'Beispiel',
    // Common actions
    'back': 'Zurück',
    'next': 'Weiter',
    'previous': 'Vorherige',
    'close': 'Schließen',
    'open': 'Öffnen',
    
    // Challenge page translations (German) - flattened structure
    'propaganda.title': challengePageTranslations.de.propaganda.title,
    'propaganda.subtitle': challengePageTranslations.de.propaganda.subtitle,
    'propaganda.definition': challengePageTranslations.de.propaganda.definition,
    'propaganda.definitionText': challengePageTranslations.de.propaganda.definitionText,
    
    'scientificConsensus.title': challengePageTranslations.de.scientificConsensus.title,
    'scientificConsensus.subtitle': challengePageTranslations.de.scientificConsensus.subtitle,
    
    'indoctrination.title': challengePageTranslations.de.indoctrination.title,
    'indoctrination.subtitle': challengePageTranslations.de.indoctrination.subtitle,
    
    'censorship.title': challengePageTranslations.de.censorship.title,
    'censorship.subtitle': challengePageTranslations.de.censorship.subtitle,
    
    'comedians.title': challengePageTranslations.de.comedians.title,
    'comedians.subtitle': challengePageTranslations.de.comedians.subtitle,
    
    'streetEpistemology.title': challengePageTranslations.de.streetEpistemology.title,
    'streetEpistemology.subtitle': challengePageTranslations.de.streetEpistemology.subtitle,
    
    'dogmaticBeliefs.title': challengePageTranslations.de.dogmaticBeliefs.title,
    'dogmaticBeliefs.subtitle': challengePageTranslations.de.dogmaticBeliefs.subtitle,
    
    'scientificMethod.title': challengePageTranslations.de.scientificMethod.title,
    'scientificMethod.subtitle': challengePageTranslations.de.scientificMethod.subtitle,
    
    'lazyThinking.title': challengePageTranslations.de.lazyThinking.title,
    'lazyThinking.subtitle': challengePageTranslations.de.lazyThinking.subtitle,
    
    'socraticQuestioning.title': challengePageTranslations.de.socraticQuestioning.title,
    'socraticQuestioning.subtitle': challengePageTranslations.de.socraticQuestioning.subtitle,
    
    'coEvolution.title': challengePageTranslations.de.coEvolution.title,
    'coEvolution.subtitle': challengePageTranslations.de.coEvolution.subtitle,
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.epistemology': 'Épistémologie',
    'nav.challenges': 'Défis',
    'nav.cognitive-biases': 'Biais Cognitifs',
    'nav.logical-fallacies': 'Sophismes Logiques',
    'nav.critical-thinking': 'Pensée Critique',
    'nav.consciousness': 'Conscience',
    'nav.solutions': 'Solutions',
    'nav.street-epistemology': 'Épistémologie de Rue',
    'nav.socratic-questioning': 'Questionnement Socratique',
    'nav.scientific-method': 'Méthode Scientifique',
    'nav.comedians': 'Comédiens',
    'nav.consensus': 'Consensus Scientifique',
    'nav.censorship': 'Censure',
    'nav.language': 'Langue',
    'home.title': 'Réalité Objective',
    'home.subtitle': 'Comprendre les biais cognitifs, les sophismes logiques et la conscience',
    'home.description': 'Explorez les modèles systématiques de déviation de la rationalité dans le jugement et la prise de décision.',
    'epistemology.title': 'Épistémologie',
    'epistemology.description': 'Comment pouvons-nous savoir si quelque chose est vraiment vrai ?',
    'challenges.title': 'Défis',
    'challenges.description': 'Barrières qui nous séparent de la réalité objective',
    'biases.title': 'Biais Cognitifs',
    'biases.description': 'Erreurs systématiques de pensée qui affectent les décisions et les jugements',
    'fallacies.title': 'Sophismes Logiques',
    'fallacies.description': 'Modèles de raisonnement défaillants qui sapent la logique d\'un argument',
    'consciousness.title': 'Conscience',
    'consciousness.description': 'Comprendre les niveaux de conscience et de développement humains',
    'consensus.title': 'Consensus Scientifique',
    'consensus.description': 'Analyse critique de l\'autorité scientifique et de la pensée de groupe',
    'solutions.title': 'Solutions',
    'solutions.description': 'Outils et méthodes pratiques pour surmonter les limitations cognitives',
    // Challenges content
    'challenges.why.title': 'Pourquoi comprendre ces défis est important',
    'challenges.personal.title': 'Croissance Personnelle',
    'challenges.personal.description': 'La conscience de nos limitations cognitives conduit à une meilleure prise de décision',
    'challenges.societal.title': 'Progrès Sociétal',
    'challenges.societal.description': 'Une population informée prend de meilleures décisions collectives',
    'challenges.discourse.title': 'Discours Amélioré',
    'challenges.discourse.description': 'Reconnaître les sophismes mène à des discussions plus productives',
    'challenges.scientific.title': 'Avancement Scientifique',
    'challenges.scientific.description': 'La pensée critique favorise une meilleure recherche et innovation',
    'challenges.start_journey': 'Commencez Votre Voyage',
    'challenges.start_journey.description': 'Commencez par explorer les défis les plus fondamentaux à la pensée claire.',
    'challenges.explore_biases': 'Explorer les Biais Cognitifs',
    'challenges.study_fallacies': 'Étudier les Sophismes Logiques',
    'challenges.advanced_topics': 'Sujets Avancés',
    'challenges.advanced_topics.description': 'Plongez plus profondément dans les barrières systémiques et culturelles à la pensée objective.',
    'challenges.scientific_consensus': 'Consensus Scientifique',
    'challenges.information_suppression': 'Suppression d\'Information',
    
    // Individual challenge items
    'challenge.indoctrination.title': 'Endoctrinement',
    'challenge.indoctrination.description': 'Influence systématique des parents, de l\'État/école et des médias qui façonne notre vision du monde dès l\'enfance.',
    'challenge.consensus.title': 'Consensus Scientifique comme Veau d\'Or',
    'challenge.consensus.description': 'Acceptation aveugle du consensus scientifique sans évaluation critique des hypothèses sous-jacentes.',
    'challenge.cognitive_biases.title': 'Biais Cognitifs',
    'challenge.cognitive_biases.description': 'Erreurs systématiques de pensée qui affectent les décisions et les jugements.',
    'challenge.logical_fallacies.title': 'Sophismes Logiques',
    'challenge.logical_fallacies.description': 'Modèles de raisonnement défaillants qui compromettent la logique des arguments.',
    'challenge.propaganda.title': 'Propagande',
    'challenge.propaganda.description': 'Informations conçues pour promouvoir des causes politiques particulières ou des points de vue.',
    'challenge.censorship.title': 'Censure',
    'challenge.censorship.description': 'Suppression d\'informations et d\'idées qui remettent en question les narratifs établis.',
    'challenge.dogmas.title': 'Croyances Dogmatiques',
    'challenge.dogmas.description': 'Adhésion rigide aux principes sans considération des preuves ou des points de vue alternatifs.',
    'challenge.co_evolution.title': 'Co-évolution avec la Religion',
    'challenge.co_evolution.description': 'Comment les modèles de pensée religieuse influencent le raisonnement et la prise de décision séculiers.',
    'challenge.lazy_thinking.title': 'Pensée Paresseuse',
    'challenge.lazy_thinking.description': 'Raccourcis mentaux et évitement d\'analyses approfondies menant à de mauvaises conclusions.',
    'challenge.psychological_weakness.title': 'Faiblesses Psychologiques',
    'challenge.psychological_weakness.description': 'Vulnérabilités psychologiques humaines qui peuvent être exploitées pour manipuler la pensée.',
    'challenge.ego.title': 'Ego',
    'challenge.ego.description': 'Comment l\'identité personnelle et l\'image de soi interfèrent avec le raisonnement objectif.',
    
    // Category translations
    'category.too_much_information': 'Trop d\'informations',
    'category.not_enough_meaning': 'Pas assez de sens',
    'category.need_to_act_fast': 'Besoin d\'agir vite',
    'category.what_to_remember': 'Que devons-nous retenir',
    'category.relevance': 'Pertinence',
    'category.presumption': 'Présomption',
    'category.weak_inference': 'Inférence faible',
    'category.causal': 'Causal',
    'category.formal': 'Formel',
    'category.conditional': 'Conditionnel',
    // Search and filter
    'search.placeholder': 'Rechercher...',
    'filter.all': 'Toutes les Catégories',
    'filter.by_category': 'Filtrer par catégorie',
    'showing_results': 'Affichage de {count} sur {total}',
    'no_results': 'Aucun résultat trouvé',
    'clear_filters': 'Effacer les Filtres',
    'learn_more': 'En savoir plus',
    'example': 'Exemple',
    // Common actions
    'back': 'Retour',
    'next': 'Suivant',
    'previous': 'Précédent',
    'close': 'Fermer',
    'open': 'Ouvrir',
    
    // Challenge page translations (French) - placeholder for now
    'propaganda.title': 'Propagande',
    'propaganda.subtitle': 'Reconnaître et résister à la guerre informationnelle moderne',
    'propaganda.definition': 'Qu\'est-ce que la propagande ?',
    'propaganda.definitionText': 'La propagande est la diffusion systématique d\'informations, d\'idées ou de rumeurs pour aider ou nuire à une institution, une cause ou une personne.',
    
    'scientificConsensus.title': 'Consensus Scientifique',
    'scientificConsensus.subtitle': 'Une évaluation personnelle de la fiabilité des connaissances scientifiques',
    
    'indoctrination.title': 'Endoctrinement',
    'indoctrination.subtitle': 'Le conditionnement systématique des croyances',
    
    'censorship.title': 'Censure',
    'censorship.subtitle': 'Formes modernes de contrôle de l\'information',
    
    'comedians.title': 'Comédiens',
    'comedians.subtitle': 'Les bouffons de cour modernes de la vérité',
    
    'streetEpistemology.title': 'Épistémologie de Rue',
    'streetEpistemology.subtitle': 'Une méthode pour examiner les croyances par le questionnement socratique',
    
    'dogmaticBeliefs.title': 'Croyances Dogmatiques',
    'dogmaticBeliefs.subtitle': 'Reconnaître et surmonter la pensée rigide',
    
    'scientificMethod.title': 'La Méthode Scientifique',
    'scientificMethod.subtitle': 'Un outil pour la recherche objective de la vérité',
    
    'lazyThinking.title': 'Pensée Paresseuse',
    'lazyThinking.subtitle': 'L\'épidémie cognitive de notre époque',
    
    'socraticQuestioning.title': 'Questionnement Socratique',
    'socraticQuestioning.subtitle': 'L\'art du questionnement discipliné',
    
    'coEvolution.title': 'Co-évolution',
    'coEvolution.subtitle': 'Comment les modèles de pensée religieuse survivent dans les contextes séculaires',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.epistemology': 'Epistemología',
    'nav.challenges': 'Desafíos',
    'nav.cognitive-biases': 'Sesgos Cognitivos',
    'nav.logical-fallacies': 'Falacias Lógicas',
    'nav.critical-thinking': 'Pensamiento Crítico',
    'nav.consciousness': 'Conciencia',
    'nav.solutions': 'Soluciones',
    'nav.street-epistemology': 'Epistemología Callejera',
    'nav.socratic-questioning': 'Cuestionamiento Socrático',
    'nav.scientific-method': 'Método Científico',
    'nav.comedians': 'Comediantes',
    'nav.consensus': 'Consenso Científico',
    'nav.censorship': 'Censura',
    'nav.language': 'Idioma',
    'home.title': 'Realidad Objetiva',
    'home.subtitle': 'Entender los sesgos cognitivos, falacias lógicas y conciencia',
    'home.description': 'Explora los patrones sistemáticos de desviación de la racionalidad en el juicio y la toma de decisiones.',
    'epistemology.title': 'Epistemología',
    'epistemology.description': '¿Cómo podemos saber si algo es realmente verdadero?',
    'challenges.title': 'Desafíos',
    'challenges.description': 'Barreras que nos separan de la realidad objetiva',
    'biases.title': 'Sesgos Cognitivos',
    'biases.description': 'Errores sistemáticos en el pensamiento que afectan decisiones y juicios',
    'fallacies.title': 'Falacias Lógicas',
    'fallacies.description': 'Patrones de razonamiento defectuosos que socavan la lógica de un argumento',
    'consciousness.title': 'Conciencia',
    'consciousness.description': 'Entender los niveles de conciencia y desarrollo humano',
    'consensus.title': 'Consenso Científico',
    'consensus.description': 'Análisis crítico de la autoridad científica y el pensamiento grupal',
    'solutions.title': 'Soluciones',
    'solutions.description': 'Herramientas y métodos prácticos para superar las limitaciones cognitivas',
    // Challenges content
    'challenges.why.title': 'Por qué entender estos desafíos es importante',
    'challenges.personal.title': 'Crecimiento Personal',
    'challenges.personal.description': 'La autoconciencia de nuestras limitaciones cognitivas lleva a una mejor toma de decisiones',
    'challenges.societal.title': 'Progreso Social',
    'challenges.societal.description': 'Una población informada toma mejores decisiones colectivas',
    'challenges.discourse.title': 'Discurso Mejorado',
    'challenges.discourse.description': 'Reconocer las falacias lleva a discusiones más productivas',
    'challenges.scientific.title': 'Avance Científico',
    'challenges.scientific.description': 'El pensamiento crítico promueve mejor investigación e innovación',
    'challenges.start_journey': 'Comienza Tu Viaje',
    'challenges.start_journey.description': 'Comienza explorando los desafíos más fundamentales para el pensamiento claro.',
    'challenges.explore_biases': 'Explorar Sesgos Cognitivos',
    'challenges.study_fallacies': 'Estudiar Falacias Lógicas',
    'challenges.advanced_topics': 'Temas Avanzados',
    'challenges.advanced_topics.description': 'Profundiza en las barreras sistémicas y culturales al pensamiento objetivo.',
    'challenges.scientific_consensus': 'Consenso Científico',
    'challenges.information_suppression': 'Supresión de Información',
    
    // Individual challenge items
    'challenge.indoctrination.title': 'Adoctrinamiento',
    'challenge.indoctrination.description': 'Influencia sistemática de padres, estado/escuela y medios que forma nuestra visión del mundo desde la infancia.',
    'challenge.consensus.title': 'Consenso Científico como Becerro de Oro',
    'challenge.consensus.description': 'Aceptación ciega del consenso científico sin evaluación crítica de las suposiciones subyacentes.',
    'challenge.cognitive_biases.title': 'Sesgos Cognitivos',
    'challenge.cognitive_biases.description': 'Errores sistemáticos en el pensamiento que afectan las decisiones y juicios.',
    'challenge.logical_fallacies.title': 'Falacias Lógicas',
    'challenge.logical_fallacies.description': 'Patrones de razonamiento defectuosos que socavan la lógica de los argumentos.',
    'challenge.propaganda.title': 'Propaganda',
    'challenge.propaganda.description': 'Información diseñada para promover causas políticas particulares o puntos de vista.',
    'challenge.censorship.title': 'Censura',
    'challenge.censorship.description': 'Supresión de información e ideas que desafían las narrativas establecidas.',
    'challenge.dogmas.title': 'Creencias Dogmáticas',
    'challenge.dogmas.description': 'Adherencia rígida a principios sin consideración de evidencia o puntos de vista alternativos.',
    'challenge.co_evolution.title': 'Co-evolución con la Religión',
    'challenge.co_evolution.description': 'Cómo los patrones de pensamiento religioso influyen en el razonamiento y la toma de decisiones seculares.',
    'challenge.lazy_thinking.title': 'Pensamiento Perezoso',
    'challenge.lazy_thinking.description': 'Atajos mentales y evitación del análisis profundo que llevan a conclusiones pobres.',
    'challenge.psychological_weakness.title': 'Debilidades Psicológicas',
    'challenge.psychological_weakness.description': 'Vulnerabilidades psicológicas humanas que pueden ser explotadas para manipular el pensamiento.',
    'challenge.ego.title': 'Ego',
    'challenge.ego.description': 'Cómo la identidad personal y la autoimagen interfieren con el razonamiento objetivo.',
    
    // Category translations
    'category.too_much_information': 'Demasiada información',
    'category.not_enough_meaning': 'No hay suficiente significado',
    'category.need_to_act_fast': 'Necesidad de actuar rápido',
    'category.what_to_remember': 'Qué deberíamos recordar',
    'category.relevance': 'Relevancia',
    'category.presumption': 'Presunción',
    'category.weak_inference': 'Inferencia débil',
    'category.causal': 'Causal',
    'category.formal': 'Formal',
    'category.conditional': 'Condicional',
    // Search and filter
    'search.placeholder': 'Buscar...',
    'filter.all': 'Todas las Categorías',
    'filter.by_category': 'Filtrar por categoría',
    'showing_results': 'Mostrando {count} de {total}',
    'no_results': 'No se encontraron resultados',
    'clear_filters': 'Limpiar Filtros',
    'learn_more': 'Aprender Más',
    'example': 'Ejemplo',
    // Common actions
    'back': 'Atrás',
    'next': 'Siguiente',
    'previous': 'Anterior',
    'close': 'Cerrar',
    'open': 'Abrir',
    
    // Challenge page translations (Spanish) - placeholder for now
    'propaganda.title': 'Propaganda',
    'propaganda.subtitle': 'Reconociendo y resistiendo la guerra de información moderna',
    'propaganda.definition': '¿Qué es la propaganda?',
    'propaganda.definitionText': 'La propaganda es la difusión sistemática de información, ideas o rumores para ayudar o dañar a una institución, causa o persona.',
    
    'scientificConsensus.title': 'Consenso Científico',
    'scientificConsensus.subtitle': 'Una evaluación personal de la confiabilidad del conocimiento científico',
    
    'indoctrination.title': 'Adoctrinamiento',
    'indoctrination.subtitle': 'El condicionamiento sistemático de las creencias',
    
    'censorship.title': 'Censura',
    'censorship.subtitle': 'Formas modernas de control de información',
    
    'comedians.title': 'Comediantes',
    'comedians.subtitle': 'Los bufones de la corte modernos de la verdad',
    
    'streetEpistemology.title': 'Epistemología Callejera',
    'streetEpistemology.subtitle': 'Un método para examinar creencias a través del cuestionamiento socrático',
    
    'dogmaticBeliefs.title': 'Creencias Dogmáticas',
    'dogmaticBeliefs.subtitle': 'Reconociendo y superando el pensamiento rígido',
    
    'scientificMethod.title': 'El Método Científico',
    'scientificMethod.subtitle': 'Una herramienta para la búsqueda objetiva de la verdad',
    
    'lazyThinking.title': 'Pensamiento Perezoso',
    'lazyThinking.subtitle': 'La epidemia cognitiva de nuestro tiempo',
    
    'socraticQuestioning.title': 'Cuestionamiento Socrático',
    'socraticQuestioning.subtitle': 'El arte del cuestionamiento disciplinado',
    
    'coEvolution.title': 'Co-evolución',
    'coEvolution.subtitle': 'Cómo los patrones de pensamiento religioso sobreviven en contextos seculares',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}