import { useLanguage } from '@/hooks/useLanguage';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';

export default function CriticalThinking() {
  const { t } = useLanguage();

  return (
    <div className="min-h-screen py-8">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Header */}
        <Card className="mb-8 glass-card">
          <CardHeader>
            <CardTitle className="text-4xl font-bold">
              Critical Thinking
            </CardTitle>
            <CardDescription className="text-xl max-w-3xl">
              The objective analysis and evaluation of an issue in order to form a judgment. Critical thinking is the foundation of rational decision-making and intellectual independence.
            </CardDescription>
          </CardHeader>
        </Card>

        {/* What is Critical Thinking Card */}
        <Card className="mb-8 glass-card">
          <CardHeader>
            <CardTitle className="text-3xl font-semibold">What is Critical Thinking?</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-muted-foreground">
              Critical thinking is the intellectually disciplined process of actively and skillfully conceptualizing, applying, analyzing, synthesizing, and evaluating information gathered from, or generated by, observation, experience, reflection, reasoning, or communication, as a guide to belief and action.
            </p>
            <p className="text-muted-foreground">
              It involves the careful acquisition and interpretation of information and the use of it to reach a well-justified conclusion. The list of core critical thinking skills includes observation, interpretation, analysis, inference, evaluation, explanation, and metacognition.
            </p>
          </CardContent>
        </Card>

        {/* Core Components Card */}
        <Card className="mb-8 glass-card">
          <CardHeader>
            <CardTitle className="text-3xl font-semibold">Core Components of Critical Thinking</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-6 md:grid-cols-2">
              <Card className="glass-card">
                <CardHeader>
                  <CardTitle className="text-xl">Analysis</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-muted-foreground">
                    Breaking down complex information into smaller parts to understand the relationships between concepts, identify patterns, and examine underlying assumptions.
                  </p>
                </CardContent>
              </Card>
              <Card className="glass-card">
                <CardHeader>
                  <CardTitle className="text-xl">Evaluation</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-muted-foreground">
                    Assessing the credibility of sources, the strength of evidence, the validity of arguments, and the reliability of conclusions drawn from available information.
                  </p>
                </CardContent>
              </Card>
              <Card className="glass-card">
                <CardHeader>
                  <CardTitle className="text-xl">Inference</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-muted-foreground">
                    Drawing logical conclusions based on available evidence while recognizing the difference between what is implied and what is explicitly stated.
                  </p>
                </CardContent>
              </Card>
              <Card className="glass-card">
                <CardHeader>
                  <CardTitle className="text-xl">Interpretation</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-muted-foreground">
                    Understanding the meaning and significance of information, recognizing context, and comprehending the implications of various perspectives.
                  </p>
                </CardContent>
              </Card>
            </div>
          </CardContent>
        </Card>

        {/* Skills and Strategies Card */}
        <Card className="mb-8 glass-card">
          <CardHeader>
            <CardTitle className="text-3xl font-semibold">Essential Critical Thinking Skills</CardTitle>
          </CardHeader>
          <CardContent className="space-y-6">
            <Card className="glass-card">
              <CardHeader>
                <CardTitle className="text-lg">Questioning Assumptions</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground mb-4">
                  Challenge underlying beliefs and assumptions that may be taken for granted. Ask questions like:
                </p>
                <ul className="list-disc list-inside text-muted-foreground space-y-1 ml-4">
                  <li>What assumptions am I making?</li>
                  <li>Are these assumptions justified?</li>
                  <li>What if the opposite were true?</li>
                  <li>What evidence supports this assumption?</li>
                </ul>
              </CardContent>
            </Card>
            
            <Card className="glass-card">
              <CardHeader>
                <CardTitle className="text-lg">Examining Evidence</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground mb-4">
                  Evaluate the quality, relevance, and sufficiency of evidence:
                </p>
                <ul className="list-disc list-inside text-muted-foreground space-y-1 ml-4">
                  <li>Is the source credible and unbiased?</li>
                  <li>Is the evidence relevant to the claim?</li>
                  <li>Is there sufficient evidence to support the conclusion?</li>
                  <li>What evidence might contradict this conclusion?</li>
                </ul>
              </CardContent>
            </Card>

            <Card className="glass-card">
              <CardHeader>
                <CardTitle className="text-lg">Considering Multiple Perspectives</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground mb-4">
                  Actively seek out and consider different viewpoints:
                </p>
                <ul className="list-disc list-inside text-muted-foreground space-y-1 ml-4">
                  <li>What other ways could this be interpreted?</li>
                  <li>Who might disagree with this conclusion and why?</li>
                  <li>What are the strengths and weaknesses of alternative views?</li>
                  <li>How might cultural or personal biases influence interpretation?</li>
                </ul>
              </CardContent>
            </Card>

            <Card className="glass-card">
              <CardHeader>
                <CardTitle className="text-lg">Logical Reasoning</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground mb-4">
                  Use sound logical principles to evaluate arguments:
                </p>
                <ul className="list-disc list-inside text-muted-foreground space-y-1 ml-4">
                  <li>Do the premises logically support the conclusion?</li>
                  <li>Are there any logical fallacies present?</li>
                  <li>Is the reasoning consistent throughout?</li>
                  <li>Are there gaps in the logical chain?</li>
                </ul>
              </CardContent>
            </Card>
          </CardContent>
        </Card>

        {/* Barriers to Critical Thinking Card */}
        <Card className="mb-8 glass-card">
          <CardHeader>
            <CardTitle className="text-3xl font-semibold">Common Barriers to Critical Thinking</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4 md:grid-cols-2">
              <Card className="glass-card">
                <CardHeader className="pb-3">
                  <CardTitle className="text-base">Confirmation Bias</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-muted-foreground">
                    Seeking information that confirms existing beliefs while avoiding contradictory evidence.
                  </p>
                </CardContent>
              </Card>
              <Card className="glass-card">
                <CardHeader className="pb-3">
                  <CardTitle className="text-base">Emotional Reasoning</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-muted-foreground">
                    Letting emotions override logical analysis and evidence-based reasoning.
                  </p>
                </CardContent>
              </Card>
              <Card className="glass-card">
                <CardHeader className="pb-3">
                  <CardTitle className="text-base">Groupthink</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-muted-foreground">
                    Conforming to group consensus without critical evaluation of alternatives.
                  </p>
                </CardContent>
              </Card>
              <Card className="glass-card">
                <CardHeader className="pb-3">
                  <CardTitle className="text-base">Authority Bias</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-muted-foreground">
                    Accepting claims simply because they come from perceived authority figures.
                  </p>
                </CardContent>
              </Card>
              <Card className="glass-card">
                <CardHeader className="pb-3">
                  <CardTitle className="text-base">Black-and-White Thinking</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-muted-foreground">
                    Seeing issues in absolute terms without recognizing nuance or complexity.
                  </p>
                </CardContent>
              </Card>
              <Card className="glass-card">
                <CardHeader className="pb-3">
                  <CardTitle className="text-base">Information Overload</CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-sm text-muted-foreground">
                    Being overwhelmed by too much information, leading to mental shortcuts and poor decisions.
                  </p>
                </CardContent>
              </Card>
            </div>
          </CardContent>
        </Card>

        {/* Developing Critical Thinking Card */}
        <Card className="mb-8 glass-card">
          <CardHeader>
            <CardTitle className="text-3xl font-semibold">How to Develop Critical Thinking Skills</CardTitle>
          </CardHeader>
          <CardContent className="space-y-6">
            <Card className="glass-card float-card hover:glow-primary transition-all duration-300">
              <CardHeader>
                <CardTitle className="text-lg">Practice Active Reading and Listening</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground">
                  Don't just consume information passively. Ask questions, take notes, and engage with the material. Look for the main arguments, evidence presented, and underlying assumptions.
                </p>
              </CardContent>
            </Card>
            
            <Card className="glass-card float-card hover:glow-primary transition-all duration-300">
              <CardHeader>
                <CardTitle className="text-lg">Ask Powerful Questions</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground">
                  Develop a habit of asking probing questions: Why is this important? What evidence supports this? What are the implications? Who benefits from this perspective? What's being left out?
                </p>
              </CardContent>
            </Card>

            <Card className="glass-card float-card hover:glow-primary transition-all duration-300">
              <CardHeader>
                <CardTitle className="text-lg">Seek Diverse Sources</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground">
                  Expose yourself to different viewpoints, cultures, and sources of information. This helps you recognize your own biases and understand complex issues from multiple angles.
                </p>
              </CardContent>
            </Card>

            <Card className="glass-card float-card hover:glow-primary transition-all duration-300">
              <CardHeader>
                <CardTitle className="text-lg">Practice Metacognition</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground">
                  Think about your thinking. Reflect on your reasoning process, identify your biases, and evaluate the effectiveness of your problem-solving strategies.
                </p>
              </CardContent>
            </Card>

            <Card className="glass-card float-card hover:glow-primary transition-all duration-300">
              <CardHeader>
                <CardTitle className="text-lg">Embrace Intellectual Humility</CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-muted-foreground">
                  Acknowledge what you don't know and be willing to change your mind when presented with better evidence. Recognize that being wrong is an opportunity to learn and grow.
                </p>
              </CardContent>
            </Card>
          </CardContent>
        </Card>

        {/* Benefits Card */}
        <Card className="mb-8 glass-card">
          <CardHeader>
            <CardTitle className="text-3xl font-semibold">Benefits of Critical Thinking</CardTitle>
          </CardHeader>
          <CardContent>
            <Card className="glass-card">
              <CardContent className="pt-6">
                <div className="grid gap-6 md:grid-cols-2">
                  <div>
                    <h4 className="font-semibold text-foreground mb-3">Personal Benefits</h4>
                    <ul className="list-disc list-inside text-muted-foreground space-y-2 text-sm">
                      <li>Better decision-making</li>
                      <li>Increased self-awareness</li>
                      <li>Enhanced problem-solving abilities</li>
                      <li>Greater intellectual independence</li>
                      <li>Reduced susceptibility to manipulation</li>
                    </ul>
                  </div>
                  <div>
                    <h4 className="font-semibold text-foreground mb-3">Professional Benefits</h4>
                    <ul className="list-disc list-inside text-muted-foreground space-y-2 text-sm">
                      <li>Improved analytical skills</li>
                      <li>Better strategic thinking</li>
                      <li>Enhanced creativity and innovation</li>
                      <li>More effective communication</li>
                      <li>Stronger leadership capabilities</li>
                    </ul>
                  </div>
                </div>
              </CardContent>
            </Card>
          </CardContent>
        </Card>

        {/* Conclusion Card */}
        <Card className="mb-8 glass-card">
          <CardHeader>
            <CardTitle className="text-2xl font-semibold">The Path Forward</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-muted-foreground">
              Critical thinking is not just an academic skill—it's a life skill that enables us to navigate an increasingly complex world. In an age of information overload, fake news, and sophisticated manipulation techniques, the ability to think critically has never been more important.
            </p>
            <p className="text-muted-foreground">
              By developing strong critical thinking skills, we become more effective problem-solvers, better communicators, and more thoughtful citizens. We learn to question our own assumptions, consider multiple perspectives, and make decisions based on evidence rather than emotion or bias. This is the foundation of intellectual freedom and rational discourse.
            </p>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}