import { useLanguage } from '@/hooks/useLanguage';

export default function CriticalThinking() {
  const { t } = useLanguage();

  return (
    <div className="container mx-auto px-4 py-8 max-w-4xl">
      <div className="space-y-8">
        {/* Header Card */}
        <div className="bg-card p-8 rounded-lg border border-border">
          <div className="text-center space-y-4">
            <h1 className="text-4xl font-bold bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent">
              Critical Thinking
            </h1>
            <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
              The objective analysis and evaluation of an issue in order to form a judgment. Critical thinking is the foundation of rational decision-making and intellectual independence.
            </p>
          </div>
        </div>

        {/* What is Critical Thinking Card */}
        <div className="bg-card p-6 rounded-lg border border-border">
          <h2 className="text-3xl font-semibold text-foreground mb-6">What is Critical Thinking?</h2>
          <div className="prose prose-lg max-w-none text-muted-foreground space-y-4">
            <p>
              Critical thinking is the intellectually disciplined process of actively and skillfully conceptualizing, applying, analyzing, synthesizing, and evaluating information gathered from, or generated by, observation, experience, reflection, reasoning, or communication, as a guide to belief and action.
            </p>
            <p>
              It involves the careful acquisition and interpretation of information and the use of it to reach a well-justified conclusion. The list of core critical thinking skills includes observation, interpretation, analysis, inference, evaluation, explanation, and metacognition.
            </p>
          </div>
        </div>

        {/* Core Components Card */}
        <div className="bg-card p-6 rounded-lg border border-border">
          <h2 className="text-3xl font-semibold text-foreground mb-6">Core Components of Critical Thinking</h2>
          <div className="grid gap-6 md:grid-cols-2">
            <div className="bg-background p-6 rounded-lg border border-border">
              <h3 className="text-xl font-semibold mb-3 text-accent-foreground">Analysis</h3>
              <p className="text-muted-foreground">
                Breaking down complex information into smaller parts to understand the relationships between concepts, identify patterns, and examine underlying assumptions.
              </p>
            </div>
            <div className="bg-background p-6 rounded-lg border border-border">
              <h3 className="text-xl font-semibold mb-3 text-accent-foreground">Evaluation</h3>
              <p className="text-muted-foreground">
                Assessing the credibility of sources, the strength of evidence, the validity of arguments, and the reliability of conclusions drawn from available information.
              </p>
            </div>
            <div className="bg-background p-6 rounded-lg border border-border">
              <h3 className="text-xl font-semibold mb-3 text-accent-foreground">Inference</h3>
              <p className="text-muted-foreground">
                Drawing logical conclusions based on available evidence while recognizing the difference between what is implied and what is explicitly stated.
              </p>
            </div>
            <div className="bg-background p-6 rounded-lg border border-border">
              <h3 className="text-xl font-semibold mb-3 text-accent-foreground">Interpretation</h3>
              <p className="text-muted-foreground">
                Understanding the meaning and significance of information, recognizing context, and comprehending the implications of various perspectives.
              </p>
            </div>
          </div>
        </div>

        {/* Skills and Strategies Card */}
        <div className="bg-card p-6 rounded-lg border border-border">
          <h2 className="text-3xl font-semibold text-foreground mb-6">Essential Critical Thinking Skills</h2>
          <div className="space-y-4">
            <div className="bg-card p-6 rounded-lg border border-border">
              <h3 className="text-lg font-semibold mb-3 text-accent-foreground">Questioning Assumptions</h3>
              <p className="text-muted-foreground mb-2">
                Challenge underlying beliefs and assumptions that may be taken for granted. Ask questions like:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-1 ml-4">
                <li>What assumptions am I making?</li>
                <li>Are these assumptions justified?</li>
                <li>What if the opposite were true?</li>
                <li>What evidence supports this assumption?</li>
              </ul>
            </div>
            
            <div className="bg-card p-6 rounded-lg border border-border">
              <h3 className="text-lg font-semibold mb-3 text-accent-foreground">Examining Evidence</h3>
              <p className="text-muted-foreground mb-2">
                Evaluate the quality, relevance, and sufficiency of evidence:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-1 ml-4">
                <li>Is the source credible and unbiased?</li>
                <li>Is the evidence relevant to the claim?</li>
                <li>Is there sufficient evidence to support the conclusion?</li>
                <li>What evidence might contradict this conclusion?</li>
              </ul>
            </div>

            <div className="bg-card p-6 rounded-lg border border-border">
              <h3 className="text-lg font-semibold mb-3 text-accent-foreground">Considering Multiple Perspectives</h3>
              <p className="text-muted-foreground mb-2">
                Actively seek out and consider different viewpoints:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-1 ml-4">
                <li>What other ways could this be interpreted?</li>
                <li>Who might disagree with this conclusion and why?</li>
                <li>What are the strengths and weaknesses of alternative views?</li>
                <li>How might cultural or personal biases influence interpretation?</li>
              </ul>
            </div>

            <div className="bg-card p-6 rounded-lg border border-border">
              <h3 className="text-lg font-semibold mb-3 text-accent-foreground">Logical Reasoning</h3>
              <p className="text-muted-foreground mb-2">
                Use sound logical principles to evaluate arguments:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-1 ml-4">
                <li>Do the premises logically support the conclusion?</li>
                <li>Are there any logical fallacies present?</li>
                <li>Is the reasoning consistent throughout?</li>
                <li>Are there gaps in the logical chain?</li>
              </ul>
            </div>
          </div>
        </div>

        {/* Barriers to Critical Thinking Card */}
        <div className="bg-card p-6 rounded-lg border border-border">
          <h2 className="text-3xl font-semibold text-foreground mb-6">Common Barriers to Critical Thinking</h2>
          <div className="grid gap-4 md:grid-cols-2">
            <div className="bg-background p-4 rounded-lg border border-border">
              <h4 className="font-semibold text-accent-foreground mb-2">Confirmation Bias</h4>
              <p className="text-sm text-muted-foreground">
                Seeking information that confirms existing beliefs while avoiding contradictory evidence.
              </p>
            </div>
            <div className="bg-background p-4 rounded-lg border border-border">
              <h4 className="font-semibold text-accent-foreground mb-2">Emotional Reasoning</h4>
              <p className="text-sm text-muted-foreground">
                Letting emotions override logical analysis and evidence-based reasoning.
              </p>
            </div>
            <div className="bg-background p-4 rounded-lg border border-border">
              <h4 className="font-semibold text-accent-foreground mb-2">Groupthink</h4>
              <p className="text-sm text-muted-foreground">
                Conforming to group consensus without critical evaluation of alternatives.
              </p>
            </div>
            <div className="bg-background p-4 rounded-lg border border-border">
              <h4 className="font-semibold text-accent-foreground mb-2">Authority Bias</h4>
              <p className="text-sm text-muted-foreground">
                Accepting claims simply because they come from perceived authority figures.
              </p>
            </div>
            <div className="bg-background p-4 rounded-lg border border-border">
              <h4 className="font-semibold text-accent-foreground mb-2">Black-and-White Thinking</h4>
              <p className="text-sm text-muted-foreground">
                Seeing issues in absolute terms without recognizing nuance or complexity.
              </p>
            </div>
            <div className="bg-background p-4 rounded-lg border border-border">
              <h4 className="font-semibold text-accent-foreground mb-2">Information Overload</h4>
              <p className="text-sm text-muted-foreground">
                Being overwhelmed by too much information, leading to mental shortcuts and poor decisions.
              </p>
            </div>
          </div>
        </div>

        {/* Developing Critical Thinking Card */}
        <div className="bg-card p-6 rounded-lg border border-border">
          <h2 className="text-3xl font-semibold text-foreground mb-6">How to Develop Critical Thinking Skills</h2>
          <div className="space-y-4">
            <div className="bg-gradient-to-r from-primary/10 to-secondary/10 p-6 rounded-lg border border-border">
              <h3 className="text-lg font-semibold mb-3 text-accent-foreground">Practice Active Reading and Listening</h3>
              <p className="text-muted-foreground">
                Don't just consume information passively. Ask questions, take notes, and engage with the material. Look for the main arguments, evidence presented, and underlying assumptions.
              </p>
            </div>
            
            <div className="bg-gradient-to-r from-primary/10 to-secondary/10 p-6 rounded-lg border border-border">
              <h3 className="text-lg font-semibold mb-3 text-accent-foreground">Ask Powerful Questions</h3>
              <p className="text-muted-foreground">
                Develop a habit of asking probing questions: Why is this important? What evidence supports this? What are the implications? Who benefits from this perspective? What's being left out?
              </p>
            </div>

            <div className="bg-gradient-to-r from-primary/10 to-secondary/10 p-6 rounded-lg border border-border">
              <h3 className="text-lg font-semibold mb-3 text-accent-foreground">Seek Diverse Sources</h3>
              <p className="text-muted-foreground">
                Expose yourself to different viewpoints, cultures, and sources of information. This helps you recognize your own biases and understand complex issues from multiple angles.
              </p>
            </div>

            <div className="bg-gradient-to-r from-primary/10 to-secondary/10 p-6 rounded-lg border border-border">
              <h3 className="text-lg font-semibold mb-3 text-accent-foreground">Practice Metacognition</h3>
              <p className="text-muted-foreground">
                Think about your thinking. Reflect on your reasoning process, identify your biases, and evaluate the effectiveness of your problem-solving strategies.
              </p>
            </div>

            <div className="bg-gradient-to-r from-primary/10 to-secondary/10 p-6 rounded-lg border border-border">
              <h3 className="text-lg font-semibold mb-3 text-accent-foreground">Embrace Intellectual Humility</h3>
              <p className="text-muted-foreground">
                Acknowledge what you don't know and be willing to change your mind when presented with better evidence. Recognize that being wrong is an opportunity to learn and grow.
              </p>
            </div>
          </div>
        </div>

        {/* Benefits Card */}
        <div className="bg-card p-6 rounded-lg border border-border">
          <h2 className="text-3xl font-semibold text-foreground mb-6">Benefits of Critical Thinking</h2>
          <div className="bg-gradient-to-r from-accent/10 to-primary/10 p-6 rounded-lg border border-border">
            <div className="grid gap-4 md:grid-cols-2">
              <div>
                <h4 className="font-semibold text-accent-foreground mb-2">Personal Benefits</h4>
                <ul className="list-disc list-inside text-muted-foreground space-y-1 text-sm">
                  <li>Better decision-making</li>
                  <li>Increased self-awareness</li>
                  <li>Enhanced problem-solving abilities</li>
                  <li>Greater intellectual independence</li>
                  <li>Reduced susceptibility to manipulation</li>
                </ul>
              </div>
              <div>
                <h4 className="font-semibold text-accent-foreground mb-2">Professional Benefits</h4>
                <ul className="list-disc list-inside text-muted-foreground space-y-1 text-sm">
                  <li>Improved analytical skills</li>
                  <li>Better strategic thinking</li>
                  <li>Enhanced creativity and innovation</li>
                  <li>More effective communication</li>
                  <li>Stronger leadership capabilities</li>
                </ul>
              </div>
            </div>
          </div>
        </div>

        {/* Conclusion Card */}
        <div className="bg-card p-6 rounded-lg border border-border">
          <h2 className="text-2xl font-semibold mb-4 text-foreground">The Path Forward</h2>
          <p className="text-muted-foreground mb-4">
            Critical thinking is not just an academic skill—it's a life skill that enables us to navigate an increasingly complex world. In an age of information overload, fake news, and sophisticated manipulation techniques, the ability to think critically has never been more important.
          </p>
          <p className="text-muted-foreground">
            By developing strong critical thinking skills, we become more effective problem-solvers, better communicators, and more thoughtful citizens. We learn to question our own assumptions, consider multiple perspectives, and make decisions based on evidence rather than emotion or bias. This is the foundation of intellectual freedom and rational discourse.
          </p>
        </div>
      </div>
    </div>
  );
}